services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - liquibase-migrations
    environment:
      - POSTGRES_DB=barbershop
    networks:
      - backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - app
  postgresql:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: barbershop
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/barbershop
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }

