spring:
  application:
    name: barbershop
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/barbershop
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
